ext {
    android = [
            COMPILESDK: 36,
            MINSDK: 21,
            TARGETSDK: 36,
            VERSIONCODE: 1031,
            VERSIONNAME: "2.6.8"
    ]
    sdk = [
            COMPDFKIT_SDK_VERSION : "2.6.8",
            COMPDFKIT_SDK_BUILD_TAG : "build_dev_03226198_202605141000"
    ]
}